const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function setup(){let n=0,paused=false;const frames=new Map(),timers=new Map();
 const buttons=[0,1,2].map(i=>{const classes=new Set();return {attrs:{'aria-pressed':String(i===0)},querySelector:()=>({}),getAttribute(k){return this.attrs[k];},setAttribute(k,v){this.attrs[k]=v;},getBoundingClientRect:()=>({top:100,bottom:200}),classList:{add:v=>classes.add(v),remove:v=>classes.delete(v),contains:v=>classes.has(v)}};});
 const ctx={document:{hidden:false},innerHeight:800,motionPaused:()=>paused,requestAnimationFrame:fn=>{frames.set(++n,fn);return n},cancelAnimationFrame:id=>frames.delete(id),setTimeout:fn=>{timers.set(++n,fn);return n},clearTimeout:id=>timers.delete(id)};vm.createContext(ctx);const s=fs.readFileSync('js/glass-demos.mjs','utf8');vm.runInContext(s.slice(s.indexOf('const selectionEffects ='),s.indexOf('const controllers =')),ctx);
 return {buttons,frames,timers,select:i=>ctx.selectProgram(buttons,i),frame:()=>{for(const [id,fn]of [...frames]){frames.delete(id);fn();}},finish:()=>{for(const [id,fn]of [...timers]){timers.delete(id);fn();}},pause:v=>paused=v,document:ctx.document};}
test('new selection sweeps once, then retains frosted pressed state',()=>{const x=setup();x.select(1);x.frame();assert.equal(x.buttons[1].classList.contains('program-select-flash'),true);x.finish();assert.equal(x.buttons[1].classList.contains('program-select-flash'),false);assert.equal(x.buttons[1].attrs['aria-pressed'],'true');});
test('repeated click does not restart the sweep',()=>{const x=setup();x.select(1);x.frame();const count=x.timers.size;x.select(1);assert.equal(x.frames.size,0);assert.equal(x.timers.size,count);});
test('rapid replacement cancels stale sweep without losing current state',()=>{const x=setup();x.select(1);x.select(2);assert.equal(x.frames.size,1);x.frame();assert.equal(x.buttons[1].classList.contains('program-select-flash'),false);assert.equal(x.buttons[1].attrs['aria-pressed'],'false');assert.equal(x.buttons[2].classList.contains('program-select-flash'),true);x.finish();assert.equal(x.timers.size,0);});
test('reduced motion selects immediately without scheduling an animation',()=>{const x=setup();x.pause(true);x.select(2);assert.equal(x.buttons[2].attrs['aria-pressed'],'true');assert.equal(x.frames.size,0);assert.equal(x.timers.size,0);});
test('hidden page never starts selection animation',()=>{const x=setup();x.document.hidden=true;x.select(1);assert.equal(x.frames.size,0);assert.equal(x.buttons[1].attrs['aria-pressed'],'true');});

test('slow sweep and cleanup stay synchronized',()=>{const js=fs.readFileSync('js/glass-demos.mjs','utf8'),css=fs.readFileSync('css/glass.css','utf8');assert.match(css,/program-selection-sweep 1500ms cubic-bezier\(\.4,0,\.2,1\) 1 both/);assert.match(js,/stopSelectionEffect\(button\),1600/);});
