"""Static authoring: build portfolio pages from audited existing content."""
from pathlib import Path
import re
from html import escape
from studio_design import flagship_hero, program_cover, program_discovery, rate_cover, rate_calculator, developer_workflow

ROOT = Path(__file__).resolve().parent.parent
def head(name):
    source = (ROOT / 'originals' / name).read_text(encoding='utf-8')
    h = source.split('</head>')[0]
    h = re.sub(r'<base[^>]*>', '', h)
    h = re.sub(r'<link[^>]+(?:fonts\.google|fonts\.gstatic)[^>]*>', '', h)
    h = re.sub(r'<link[^>]+href="(?:\.\./)?css/[^>]*>', '', h)
    h = re.sub(r'<style>.*?</style>', '', h, flags=re.S)
    h = h.replace('content="noindex"', 'content="index, follow"')
    ui_styles = {'index.html': ['growth', 'discount'], 'partner-growth-programs.html': ['growth'], 'discounting.html': ['discount']}.get(name, [])
    extra = ''.join(f'\n<link rel="stylesheet" href="css/{kind}-ui.css">' for kind in ui_styles)
    return h + '\n<link rel="stylesheet" href="css/folio.css">\n<link rel="stylesheet" href="css/editorial.css">\n<link rel="stylesheet" href="css/showcase.css">' + extra + '\n<link rel="stylesheet" href="css/studio.css">\n<link rel="stylesheet" href="css/concepts.css">\n<link rel="stylesheet" href="css/project-system.css">\n<link rel="preload" as="font" type="font/woff2" href="fonts/manrope-latin.woff2" crossorigin>\n<link rel="preload" as="font" type="font/woff2" href="fonts/ubuntu-mono-regular.woff2" crossorigin>\n</head>'

def nav(active=''):
    return f'''<a class="skip-link" href="#main">Skip to content</a>
<header class="site-nav"><a class="wordmark" href="index.html" aria-label="Nicholas Gwee home"><span class="header-logo-mark" aria-hidden="true">&gt;</span></a><span class="nav-identity">Nicholas Gwee<small>Product Design Lead</small></span>
<nav aria-label="Main navigation"><a href="projects.html" {'aria-current="page"' if active=='work' else ''}>Work</a><a href="index.html#about" {'aria-current="page"' if active=='about' else ''}>About</a><a href="resume.html" {'aria-current="page"' if active=='resume' else ''}>Resume</a></nav>
<a class="nav-contact" href="mailto:nicholasgweepk@gmail.com">Let’s talk <span aria-hidden="true">↗</span></a></header><button type="button" class="motion-control" data-motion-toggle aria-pressed="false" disabled>Motion off</button>'''

def footer():
    return '''<footer class="folio-footer"><p class="eyebrow">A conversation is a good place to start.</p><a class="contact-title" href="mailto:nicholasgweepk@gmail.com">Let’s talk<br>design.<span aria-hidden="true">↗</span></a><div class="footer-bottom"><span>Nicholas Gwee · Bangkok, Thailand</span><div><a href="mailto:nicholasgweepk@gmail.com">Email</a><a href="https://www.linkedin.com/in/nicholasgwee/">LinkedIn ↗</a><a href="https://github.com/nicgpk">GitHub ↗</a><a href="resume.html">Resume ↗</a></div></div></footer>'''

programs = [
('Promotions','Conversion','Property sets a discount. Agoda adds a deal badge, boosts rank, and amplifies across email, push, and deal pages.','icon-promo-3d.webp','Choose a discount type and depth: Mega Sale, Seasonal, Always-on or Targeted. Existing examples include app-user and advance-booking discounts.'),
('Agoda Growth Program','Marketing','A higher commission funds ranking boost, ad spend and a Preferred Partner badge.','icon-growth-3d.webp','Typically 10–15% incremental commission (INM). The program brings higher search rank, Google and Kayak ad spend, and wider affiliate reach.'),
('Boost Rank','Visibility','Target audiences and stay dates. Pay only when a booking lands, with no lock-in.','icon-boost-3d.webp','Choose a target audience and campaign budget. Incremental commission is charged per booking, rather than per impression.'),
('Agoda Advanced','Prepaid','Pay upfront. Agoda deducts eligible booking earnings from the balance.','icon-wallet-3d.webp','AGP and Maximum Gain variants. The original source describes the prepayment as auto-renewing when the balance hits 90%.'),
('Maximum Gain','Distribution','Share wholesale rates across airlines, banks, loyalty apps and OTAs.','icon-growth-3d.webp','A minimum 1% discount off the standard rate, with no lock-in or extra paperwork. Distribution uses the Booking Holdings affiliate network.'),
('Sponsored Listing','Placement','Buy a top sponsored slot in city search results, above organic results.','icon-boost-3d.webp','Choose a city, date range and slot (top 1–3), priced upfront. Available across platforms.'),
('Dynamic Rates','Rate automation','Automatically close the rate gap when a wholesaler undercuts.','icon-promo-3d.webp','Activate once in YCS. The existing policy allows up to 2% below the wholesaler rate, capped at 25% off.'),
('Flagship Store','Branded storefront','A bespoke branded storefront for hotel chains.','icon-wallet-3d.webp','A negotiated incremental commission and contract term support a dedicated store page, branded search suggestion and homepage banner.')]

def discovery(compact=False):
    return program_discovery(programs, symbol_ids, compact)

def growth_cover():
    return program_cover(programs, symbol_ids)

def evidence(kind):
    if kind=='growth':
        title='One hub. A shared design language.'
        metrics=[('$521M+','2025 program portfolio revenue'),('12%','Activating a program within 24 hours'),('4 / 7','Co-owned tenets / lifecycle patterns')]
        text='The portfolio revenue predates the MVP launched in Q1 2026. It describes the programs’ business scale, not revenue caused by the hub redesign. The original source does not provide a baseline or sample size for the activation figure.'
        detail='''<details><summary>Scope, research &amp; program-level evidence</summary><p>8 programs · 3 design tracks · 5+ business owners. Tested with 8 partners across 3 markets. MVP shipped in one quarter; A/B test December 2025–January 2026.</p><div class="evidence-table-wrap"><table><caption>Program estimates as reported in the original case study</caption><thead><tr><th>Program</th><th>Evidence &amp; context</th></tr></thead><tbody><tr><td>Promotions</td><td>$233M estimated revenue. Mega Sale: 755M+ impressions; Seasonal: $89.7M; Always-on: $29M; Targeted: $114.2M, 72% penetration.</td></tr><tr><td>Agoda Growth Program</td><td>$131M estimated revenue; +10% average booking uplift; 1.8× more PPC/MSE ad spend.</td></tr><tr><td>Agoda Advanced</td><td>$120M estimated revenue.</td></tr><tr><td>Maximum Gain</td><td>$75M estimated revenue; 10,000+ affiliates. Previous UI example used $54M; the program description uses $75M.</td></tr><tr><td>Boost Rank</td><td>$67M estimated revenue.</td></tr><tr><td>Sponsored Listing</td><td>$17M estimated revenue.</td></tr><tr><td>Dynamic Rates</td><td>$7.5M estimated revenue.</td></tr><tr><td>Flagship Store</td><td>30× average ROAS; +29% net room nights; +32% revenue; 160k+ daily impressions, reported for live partners.</td></tr></tbody></table></div><p>Program estimates have unspecified periods and may overlap. They are not added together or reconciled to the 2025 portfolio total. Sample property balances and predicted uplift in the original mockup are illustrative UI data, not outcomes.</p></details>'''
    elif kind=='discount':
        title='A clearer rate. Fewer complaints.'
        metrics=[('10–12%','Activation lift · original project index'),('−3%','Partner-support handle time'),('#1','Complaint category reported eliminated'),('1.5 yrs','Ongoing impact reported in source')]
        text='These are reported outcomes from the existing portfolio, not measured results of this updated concept. The source narrative calls the complaint #1; its before/after chart says “Top 3.” That ranking remains unresolved.'
        detail='''<details><summary>Research &amp; attribution context</summary><p>Tested stacking explanations with 12 partners. Workshops involved 5+ business owners. Team: 1 Product Owner, 8 Developers and 1 UX Researcher. Shipped behind feature flags; tracked handle time, activation and complaint volume. The source gives no experiment sample sizes, confidence intervals or activation baseline.</p></details>'''
    else:
        title='From working days to minutes.'
        metrics=[('6m 8s','Average service creation · formerly 1–2 days'),('68.8','Final System Usability Scale score'),('4.4/5','Reported deployment ease')]
        text='Reported outcomes across three quarters. The original results card rounds creation time to “6 Min”; the narrative gives 6m 8s. No new measurements are attributed to the updated concept.'
        detail='''<details><summary>Research, team &amp; SUS progression</summary><p>15+ developer interviews · 47 usability issues documented. Team: 1 Product Owner, 4–5 Engineers and 1 Frontend Engineer.</p><p class="sus-line">22Q4: 61.9 → 23Q2: 63.4 → 23Q4: 68.8</p><p>The existing study cites industry-average SUS of 68 and a future goal of 70+. That goal is not presented as an achieved result. The source does not provide participant counts for SUS or the deployment-ease rating.</p></details>'''
    return f'''<section class="evidence-card evidence--{kind}" id="evidence" aria-labelledby="evidence-title"><p class="eyebrow">Evidence &amp; outcomes · reported in original portfolio</p><h2 id="evidence-title">{title}</h2><dl class="evidence-metrics">{''.join(f'<div><dt>{label}</dt><dd>{num}</dd></div>' for num,label in metrics)}</dl><p class="evidence-context">{text}</p>{detail}</section>'''

symbol_ids=['promotion','growth','boost','prepaid','distribution','placement','rates','storefront']

def growth_graphic():
    positions=[(300,86),(450,149),(514,300),(450,450),(300,514),(149,450),(86,300),(149,149)]
    lines=''.join(f'<path class="program-ray {"selected" if i==0 else ""}" data-ray="{i}" d="M300 300 L{x} {y}"/>' for i,(x,y) in enumerate(positions))
    glyphs=''.join(f'<g class="program-node {"selected" if i==0 else ""}" data-symbol="{i}" transform="translate({x} {y})"><circle r="34"/><use href="images/program-symbols.svg#{symbol_ids[i]}" x="-23" y="-23" width="46" height="46"/></g>' for i,(x,y) in enumerate(positions))
    buttons=''.join(f'<button type="button" data-program-select="{i}" aria-pressed="{"true" if i==0 else "false"}" disabled>{escape(p[0])}</button>' for i,p in enumerate(programs))
    panels=''.join(f'<div data-program-panel="{i}" {"" if i==0 else "hidden"}><h4>{escape(p[0])}</h4><p>{escape(p[2])}</p><p>{escape(p[4])}</p></div>' for i,p in enumerate(programs))
    return f'''<div class="flagship-art graphic-scene" data-kinetic-scene><span class="graphic-label">Updated concept · Eight programs. One property-centered hub.</span><svg class="kinetic-disc" data-kinetic viewBox="0 0 600 600" aria-hidden="true"><circle class="growth-disc" cx="300" cy="300" r="280"/>{lines}{glyphs}<g class="property-node"><rect x="260" y="260" width="80" height="80"/><path d="m280 299 20-17 20 17v24h-40Zm15 24v-15h10v15"/><text x="300" y="367" text-anchor="middle">Property</text></g></svg></div><div class="program-browser" data-program-browser><p class="graphic-label">Explore the existing programs</p><div class="program-options" role="group" aria-label="Choose a growth program">{buttons}</div><div class="program-reading" aria-live="polite">{panels}</div><noscript><p>Open the original program catalog to read every program's mechanics.</p></noscript></div>'''

def rate_graphic():
    return '''<div class="discount-art graphic-scene" data-rate-graphic data-kinetic-scene><p class="graphic-label">Updated concept · Sequential stacking · illustrative rate</p><div class="rate-ladder" data-kinetic><div class="rate-step"><span>Starting room rate</span><strong data-rate-start>$150.00</strong><div class="rate-track"><span style="width:100%"></span></div></div><div class="rate-step"><span data-mega-label>After Mega Sale · 15%</span><strong data-rate-mega>$127.50</strong><div class="rate-track"><span data-mega-bar style="width:85%"></span></div></div><div class="rate-step"><span data-mobile-label>Then Mobile Exclusive · 10%</span><output data-rate-net for="graphic-rate">$114.75</output><div class="rate-track"><span data-net-bar style="width:76.5%"></span></div></div></div><form class="rate-controls"><label>Room rate (USD)<input disabled id="graphic-rate" name="rate" type="number" min="0" max="1000000" step="0.01" value="150" required inputmode="decimal"></label><label><input disabled type="checkbox" name="mega" checked> Mega Sale · 15%</label><label><input disabled type="checkbox" name="mobile" checked> Mobile Exclusive · 10%</label><p class="form-error" data-rate-error aria-live="polite"></p></form><noscript><p class="rate-explanation">Static example: $150 less 15%, then 10%, equals $114.75. Enable JavaScript to change the calculation.</p></noscript><p class="rate-explanation">Each discount applies to the remaining balance. Before commission and taxes.</p></div>'''

def flow_graphic():
    return '''<div class="dev-art graphic-scene" data-flow-preview data-kinetic-scene><p class="graphic-label">Updated concept · Deployment workflow · example settings</p><svg class="flow-diagram" data-kinetic viewBox="0 0 600 220" aria-hidden="true"><path class="flow-wire" d="M80 110H520"/><path class="flow-loop" d="M80 110V35H520V110M300 110v75h220V110"/><g class="flow-signal"><circle cx="80" cy="110" r="50"/><path d="m65 110 12 12 19-24"/></g><g class="flow-node"><rect x="56" y="86" width="48" height="48"/><rect x="276" y="86" width="48" height="48"/><rect x="496" y="86" width="48" height="48"/></g></svg><div class="flow-options" role="group" aria-label="Explore deployment stages"><button type="button" data-flow-select="0" aria-pressed="true" disabled>Environment</button><button type="button" data-flow-select="1" aria-pressed="false" disabled>Rollout</button><button type="button" data-flow-select="2" aria-pressed="false" disabled>Review</button></div><div class="flow-reading" aria-live="polite"><div data-flow-panel="0"><h4>staging-mesh</h4><p>Mesh cluster · 24 cores · 24 Gi</p><p>actions/ansible-runner · 98ds12df</p></div><div data-flow-panel="1" hidden><h4>Canary</h4><p class="canary-sequence">10% → 20% → 30%</p><p>Hong Kong, Singapore and Amsterdam · 10 replicas each. 300s ramp up · 900s monitoring.</p></div><div data-flow-panel="2" hidden><h4>Review the configuration.</h4><p>staging-mesh · Canary · 24 cores · 24 Gi</p><p>This graphic explores the existing workflow. No infrastructure connection or deployment.</p></div></div></div>'''

def selected():
    return f'''<section class="selected-work work-sequence" id="work" aria-labelledby="work-title"><div class="work-sequence-label"><h2 id="work-title">Selected <span>work.</span></h2><span>Product &amp; platform design · Agoda</span></div>
<article class="work-growth work-flagship"><div class="project-heading"><p class="eyebrow">Partner experience · Product Design Lead</p><h3><a href="partner-growth-programs.html">Partner<br> Growth<br> Programs.</a></h3></div><div class="project-intent"><p>I owned design strategy, information architecture and interaction design for the partner growth program suite.</p><a class="text-link" href="partner-growth-programs.html">Read the case study <span aria-hidden="true">↗</span></a></div>{growth_graphic()}<div class="project-caption"><p>One property-first hub. A common language for discovering, comparing and managing programs.</p><p class="artifact-caption">Updated concept · original program content and mechanics.<a href="originals/partner-growth-programs.html">Original portfolio artifacts ↗</a></p></div></article>
<article class="work-discount"><div class="project-heading"><p class="eyebrow">Pricing &amp; promotions · Senior Product Designer</p><h3><a href="discounting.html">Discounting<br> 2.0.</a></h3></div><div class="project-intent"><p>I led design across a high-revenue partner surface, aligning product and business owners.</p><a class="text-link" href="discounting.html">Read the case study <span aria-hidden="true">↗</span></a></div>{rate_graphic()}<div class="project-caption"><p>Make stacking understandable before commitment, then explain the booking night by night.</p><p class="artifact-caption">Updated concept · existing sequential calculation. Illustrative data.<a href="originals/discounting.html">Original portfolio artifacts ↗</a></p></div></article>
<article class="work-dev"><div class="project-heading"><p class="eyebrow">Developer experience · Senior Product Designer</p><h3><a href="dev-portal.html">Developer<br> Portal.</a></h3></div><div class="project-intent"><p>I led 0-to-1 design as the first designer in DevOps.</p><a class="text-link" href="dev-portal.html">Read the case study <span aria-hidden="true">↗</span></a></div>{flow_graphic()}<div class="project-caption"><p>A searchable catalog and a guided path from environment setup to deployment review.</p><p class="artifact-caption">Updated concept · original workflow and example settings.<a href="originals/dev-portal.html">Original portfolio artifacts ↗</a></p></div></article></section>'''


def showcase_graphic(kind):
    if kind == 'growth':
        return growth_cover()
    if kind == 'discount':
        return discount_cover()
    return '''<div class="cover-deploy"><div class="cover-deploy-header"><svg viewBox="0 0 24 24"><path d="m12 3 10 18H2Z"/></svg><span>Developer Portal</span><span>Example settings</span></div><div class="cover-deploy-steps"><span>Environment</span><span class="cover-stage-active">Rollout</span><span>Review</span></div><div class="cover-deploy-body"><div class="cover-environment"><p>Environment</p><h4>staging-mesh</h4><div><span>24 cores</span><span>24 Gi</span></div></div><div class="cover-canary"><p>Rollout strategy</p><h4>Canary</h4><div class="cover-canary-sequence"><span>10%</span><span>20%</span><span>30%</span></div><div class="cover-canary-track"><i></i><i></i><i></i></div><p>300s ramp up · 900s monitoring</p></div></div><div class="cover-deploy-footer"><span>Hong Kong · Singapore · Amsterdam</span><span>10 replicas each</span></div></div>'''

def project_showcase():
    cards=[
      ('growth','partner-growth-programs.html','Partner Growth Programs.','Product Design Lead · Partner experience','I owned design strategy, information architecture and interaction design for the partner growth program suite.','Program discovery · Existing content and mechanics.'),
      ('discount','discounting.html','Discounting 2.0.','Senior Product Designer · Pricing &amp; promotions','I led design across a high-revenue partner surface, aligning product and business owners.','Sequential stacking · Illustrative room rate.'),
      ('dev','dev-portal.html','Developer Portal.','Senior Product Designer · Developer experience','I led 0-to-1 design as the first designer in DevOps.','Deployment workflow · Existing example settings.')
    ]
    items=''.join(f'''<article class="showcase-card showcase-card--{kind}"><a class="showcase-card-link" href="{route}"><div class="showcase-card-header"><div class="showcase-heading"><p class="showcase-role">{role}</p><h3>{title}</h3></div><div class="showcase-summary"><p>{ownership}</p><span class="showcase-case-link">Read the case study <span aria-hidden="true">↗</span></span></div></div></a><div class="showcase-art showcase-art--{kind}" data-cover-scene aria-hidden="true">{showcase_graphic(kind)}</div><p class="showcase-caption">Updated concept · {caption}</p></article>''' for kind,route,title,role,ownership,caption in cards)
    return f'''<section class="selected-work project-showcase" id="work" aria-labelledby="work-title"><div class="showcase-intro"><h2 id="work-title">Selected <span>work.</span></h2><p class="showcase-hint" id="gallery-instructions">Scroll over the projects to explore. Swipe on touch screens.<span class="sr-only"> Keyboard: focus the gallery and use Left and Right arrows, Home or End. Tab through project links to read each case study.</span></p></div><div class="showcase-toolbar"><div class="showcase-navigation"><span data-showcase-status hidden role="status" aria-live="polite" aria-atomic="true"><span class="sr-only">Project </span><span data-showcase-position>1 of 3</span></span><button type="button" data-showcase-prev aria-label="Previous project" aria-controls="project-gallery" hidden disabled><span aria-hidden="true">←</span></button><button type="button" data-showcase-next aria-label="Next project" aria-controls="project-gallery" hidden><span aria-hidden="true">→</span></button><a href="projects.html">All work <span aria-hidden="true">↗</span></a></div></div><div class="showcase-track" id="project-gallery" role="region" aria-label="Selected projects" aria-describedby="gallery-instructions" tabindex="0">{items}</div></section>'''

def archive():
    return '''<section class="archive"><div class="section-heading"><p class="eyebrow">Earlier work · GovTech</p><h2>Public service.<br>Practical impact.</h2></div><div class="archive-entry"><h3>Transcribe</h3><p>0-to-1 design for a secure speech-to-text platform: live and file transcription in English, Chinese, Malay and Tamil; shared workspaces; automated minutes and summaries.</p><span class="archive-evidence">3 government agencies · reported adoption</span></div><div class="archive-entry"><h3>Centralised Data Platform</h3><p>0-to-1 design for a data subscription platform that streamlines request and approval workflows.</p><span class="archive-evidence">5+ government agencies · reported scope</span></div><a class="text-link" href="originals/projects.html">View the original project index ↗</a></section>'''

def about():
    jobs=[('Agoda · Bangkok','Product Design Lead','Oct 2025 – Present'),('Agoda · Bangkok','Senior Product Designer','Aug 2022 – Oct 2025'),('GovTech · Singapore','UX Designer','Jul 2019 – Aug 2022'),('OCBC Bank · Singapore','UX Designer','Aug 2018 – Jul 2019'),('Lucasfilm / Disney · Singapore','Look Development Designer','Aug 2015 – Jul 2018')]
    return '''<section class="about-section" id="about"><div class="leadership-copy"><p class="eyebrow">Design leadership</p><h2>Build the team.<br>Shape the product.</h2><p>I adapt the method to the challenge, staying close to users through discovery interviews, usability testing, funnel analysis, clickstreams and NPS signals.</p><p>I keep the longer-term vision in view while balancing evidence, capacity and stakeholder alignment. Design stays tied to conversion, retention, revenue and operational efficiency.</p><p>I hire, coach and build the conditions for teams to do their best work. AI tools augment research synthesis, critique, prototyping and production handoff: Cursor, Claude, GPT, DeepSeek and Figma.</p><a class="text-link" href="resume.html">Experience &amp; resume ↗</a></div><div class="about-detail"><h3>Experience</h3><ol class="experience">'''+''.join(f'<li><span>{company}</span><strong>{role}</strong><small>{dates}</small></li>' for company,role,dates in jobs)+'''</ol></div></section>'''

# Integration: replace calculator() with this function; add discount_cover(),
# and return discount_cover() from showcase_graphic('discount').
# Load css/discount-ui.css after existing styles on home and discounting only.
# Visual references: https://stripe.com/billing and
# https://docs.stripe.com/billing/subscriptions/coupons
# The calculator uses the shared cent-rounded helper; the UI exposes each balance.

def calculator():
    return rate_calculator()


def discount_cover():
    return rate_cover()

def developer():
    return developer_workflow()


def case(kind):
    data={
      'growth':('partner-growth-programs.html','Partner Growth<br>Programs.','Product Design Lead · Agoda','One hub for the whole<br>growth journey.','Owned design strategy end to end for Agoda’s partner growth program suite: from problem framing and stakeholder alignment to information architecture, interaction design and visual craft.','Every program funnel optimized its own metrics. Partners struggled to discover and compare programs, while complex programs attracted less traffic.', [('Design around the property, not the funnel.','A unified hub makes discovery and comparison part of one partner experience, with recommended actions and a full program catalog.'),('Give every program a common language.','Four co-owned tenets and seven lifecycle patterns align discovery, pre-activation confidence, activation, settings, analytics, deactivation and retention.'),('Align early. Scope the launch.','Weekly syncs with program owners surfaced tradeoffs. Partner research, support tickets and NPS informed the work; an impact/effort matrix shaped the MVP.')]),
      'discount':('discounting.html','Every discount.<br>Understood.','Senior Product Designer · Agoda','Make the economics<br>visible before commitment.','Led design for Discounting 2.0 across one of Agoda’s highest-revenue partner surfaces, aligning product and business owners while protecting the partner experience.','Partners could not tell how discounts stacked. Legacy promotions were confusing, and changes to this high-revenue surface involved conflicting stakeholder interests.', [('Show the calculation before commitment.','The Net Rate Simulator makes sequential discounting visible on the remaining balance, so a partner can understand the resulting room rate.'),('Explain the booking, night by night.','A reservation breakdown shows the promotion, percentage and monetary value for each night instead of forcing partners to reverse-engineer their earnings.'),('Teach the rule at the decision point.','Connect booker conditions to eligible promotions, then show their priority and sequence. Iterate through partner testing, feature-flagged experiments and support feedback.')]),
      'dev':('dev-portal.html','Less friction.<br>More building.','Senior Product Designer · Agoda Engineering','Give developers<br>a path they can follow.','Led 0-to-1 design for Developer Portal and Deployment as the first designer in DevOps, building domain understanding and a measurable foundation for developer experience.','The internal platform was fragmented and slow. A flat homepage and missing guidance made service creation depend on Slack and tribal knowledge, with no usability baseline.', [('Organize around the task.','Replace a flat link dump with Manage, Plan, Build, Secure and Monitor. A searchable catalog brings ownership, source and compliance into view.'),('Unblock first. Then automate.','Initial fixes added in-context guidance, skipped unused repository steps, and supported leave and resume during AD handoffs. Later work introduced automation and approval workflows.'),('Make deployment a reviewable decision.','A staged private-cloud flow covers environment setup, canary rollout across data centers, and review. Information hierarchy surfaces environments and critical actions.')])}
    route,title,role,thesis,myrole,problem,choices=data[kind]
    demo=discovery() if kind=='growth' else calculator() if kind=='discount' else developer()
    inspiration={'growth':'Shopify-inspired program discovery','discount':'Stripe-inspired calculation clarity','dev':'Vercel-inspired developer workflow'}[kind]
    extra=''
    if kind=='growth':
        extra='''<section class="supporting-artifacts"><div class="section-heading"><p class="eyebrow">Design system evidence</p><h2>Consistency across<br>the lifecycle.</h2></div><p>The original interactive playbook retains all seven patterns, their examples and the four co-owned tenets.</p><a class="text-link" href="originals/partner-growth-programs.html">Open the original lifecycle playbook &amp; product artifacts ↗</a></section>'''
    elif kind=='discount':
        extra='''<section class="supporting-artifacts"><div class="section-heading"><p class="eyebrow">Promotion breakdown · updated calculation example</p><h2>The same clarity,<br>night by night.</h2></div><div class="night-breakdown"><div><span>Night 1 · Mega Sale, 15%</span><strong>$150 − $22.50 = $127.50</strong></div><div><span>Night 2 · Mobile Exclusive, 10%</span><strong>$150 − $15.00 = $135.00</strong></div><div class="night-total"><span>Room rate after discounts · two nights</span><strong>$262.50</strong></div></div><p class="artifact-note">Illustrative example, before commission and taxes. The original artifact lists a $11.25 mobile discount on a $150 night at 10%; this updated example corrects that arithmetic to $15.00. Total discounts: $37.50.</p><a class="text-link" href="originals/discounting.html">View all three original product artifacts ↗</a></section>'''
    else:
        extra='''<section class="supporting-artifacts"><div class="section-heading"><p class="eyebrow">Research &amp; original artifacts</p><h2>Understand the blocker.<br>Then design the path.</h2></div><figure class="research-figure"><img src="images/dev_pc_research.png" width="972" height="1063" loading="lazy" decoding="async" alt="Original synthesis of developer interviews into recurring workflow themes"><figcaption>Original developer research synthesis. Full-size image and all catalog, deployment and service-detail artifacts remain accessible below.</figcaption></figure><a class="text-link" href="images/dev_pc_research.png">Open research image at full size ↗</a><a class="text-link" href="originals/dev-portal.html">View original research, before/after flow &amp; deployment screens ↗</a></section>'''
    body=f'''{nav('work')}<main id="main"><section class="case-hero case-hero--{kind}"><a class="back-link" href="projects.html">← Selected work</a><p class="eyebrow">{role}</p><h1>{title}</h1><p class="case-thesis">{thesis}</p><a class="case-scroll" href="#decisions">The decisions <span aria-hidden="true">↓</span></a></section><div class="case-body"><nav class="case-section-nav" aria-label="Case study sections"><a href="#decisions">Problem &amp; role</a><a href="#choices">Key choices</a><a href="#evidence">Evidence</a><a href="#concept">Try the concept <span aria-hidden="true">↗</span></a></nav><section class="case-framing" id="decisions"><div><p class="eyebrow">The problem</p><h2>{problem}</h2></div><div><p class="eyebrow">My role</p><p>{myrole}</p><a class="text-link" href="originals/{route}">Read the complete original case study ↗</a></div></section><section class="decisions-section" id="choices"><p class="eyebrow">Key choices</p>{''.join(f'<article class="decision"><span aria-hidden="true">↳</span><h3>{t}</h3><p>{d}</p></article>' for t,d in choices)}</section>{evidence(kind)}<section class="concept-section" id="concept"><div class="concept-heading"><div><p class="eyebrow">Updated concept · {inspiration}</p><h2>Explore the<br>design in action.</h2></div><a class="text-link" href="originals/{route}">Original artifacts ↗</a></div><p class="concept-context">A new visual exploration using the existing content and workflow. This is a portfolio concept, not an additional shipped contribution or measured outcome.</p><div class="concept-canvas concept-canvas--{kind}">{demo}</div></section>{extra}<div class="case-next"><a href="{'discounting.html' if kind=='growth' else 'dev-portal.html' if kind=='discount' else 'partner-growth-programs.html'}">Next case study <span aria-hidden="true">↗</span></a><a href="projects.html">All work</a></div></div></main>{footer()}'''
    write(route,body)

def write(name,body):
    (ROOT/name).write_text(head(name)+'\n<body class="folio">'+body+'\n<script type="module" src="js/folio.mjs"></script>\n</body>\n</html>\n',encoding='utf-8')

identity=flagship_hero()
write('index.html',nav()+f'<main id="main" class="portfolio-home">{identity}{project_showcase()}<div class="studio-divider" aria-hidden="true"><i></i><i></i><i></i></div>{about()}{archive()}</main>'+footer())
write('projects.html',nav('work')+'<main id="main"><section class="work-index-heading"><p class="eyebrow">Nicholas Gwee · Product Design Lead</p><h1>Selected work.</h1><p>Product strategy, interface craft and the evidence behind the work.</p></section>'+selected()+archive()+'</main>'+footer())
for kind in ['growth','discount','dev']: case(kind)

# Preserve the resume and its download/contact content; replace only its navigation.
resume=(ROOT/'resume.html').read_text(encoding='utf-8')
if 'site-nav' not in resume:
    resume=re.sub(r'<header class="header">.*?</header>',nav('resume'),resume,flags=re.S)
    resume=resume.replace('<main>','<main id="main">',1)
    resume=resume.replace('</head>','<link rel="stylesheet" href="css/folio.css">\n</head>')
    resume=resume.replace('<body>','<body class="resume-page">')
    (ROOT/'resume.html').write_text(resume,encoding='utf-8')
