"""Small, accessible demonstrations of the existing program and deployment tasks."""
from html import escape
from interface_icons import icon

def growth_preview(programs):
    controls=[]
    panels=[]
    for i,(name,category,desc,_,mechanics) in enumerate(programs[:3]):
        controls.append(f'''<button class="lean-program {'is-selected' if i==0 else ''}" id="preview-program-{i}" type="button" role="tab" aria-selected="{'true' if i==0 else 'false'}" aria-controls="preview-program-detail-{i}" tabindex="{0 if i==0 else -1}" data-preview-choice="{i}" disabled><span><strong>{escape(name)}</strong><small>{escape(category)}</small></span>{icon('arrow-right')}</button>''')
        extra='<div class="lean-mechanics"><span>Discount types</span><div><span>Mega Sale</span><span>Seasonal</span><span>Always-on</span><span>Targeted</span></div></div>' if i==0 else f'<div class="lean-mechanics"><span>How it works</span><p>{escape(mechanics)}</p></div>'
        panels.append(f'''<div class="lean-detail preview-pane preview-detail" id="preview-program-detail-{i}" role="tabpanel" aria-labelledby="preview-program-{i}" data-preview-panel="{i}" {'' if i==0 else 'hidden'}><div class="lean-detail-heading"><span>{escape(category.upper())}</span><span class="lean-percent" aria-hidden="true">{icon(['percent','megaphone','trending-up'][i])}</span></div><h4>{escape(name)}</h4><p>{escape(desc)}</p>{extra}</div>''')
    return f'''<div class="product-preview catalog-preview catalog-preview--lean concept-shell concept-preview" data-preview-picker data-picker-direction="vertical"><div class="lean-heading preview-header"><h4>Growth programs</h4><span>Explore the options for your property.</span></div><div class="lean-catalog preview-body"><div class="lean-results preview-pane"><p class="lean-label">All categories <span>3 of 8 programs</span></p><div class="preview-choices" role="tablist" aria-label="Program examples" aria-orientation="vertical">{''.join(controls)}</div></div><div class="preview-panels">{''.join(panels)}</div></div><div class="preview-note"><span>Explore programs by goal.</span></div></div>'''

def discount_preview():
    return '''<div class="product-preview rate-preview concept-shell concept-preview" data-discount-preview><div class="preview-header"><h4>Net Rate Simulator</h4><span>USD / night · Before commission and taxes</span></div><form class="preview-discounts" aria-label="Sample discounts"><label><input type="checkbox" name="mega" checked disabled> Mega Sale <span>15%</span></label><label><input type="checkbox" name="mobile" checked disabled> Mobile Exclusive <span>10%</span></label></form><div class="rate-preview-body preview-body"><div class="rate-preview-overview preview-pane"><p class="rate-preview-eyebrow">ROOM RATE AFTER DISCOUNTS</p><div class="rate-preview-result"><strong data-preview-net>$114.75</strong><span><b data-preview-effective>23.5%</b><small>effective discount</small></span></div><p class="rate-preview-exclusion">Before commission and taxes</p><div class="rate-preview-formula" data-preview-formula>150 × 0.85 × 0.90 = 114.75</div></div><div class="rate-preview-steps preview-pane preview-detail"><div><span>Starting room rate</span><strong>$150.00</strong><i style="--rate-width:100%"></i></div><div><span data-preview-mega-label>Mega Sale <b>15%</b></span><strong data-preview-mega>$127.50</strong><small data-preview-mega-cut>−$22.50</small><i data-preview-mega-bar style="--rate-width:85%"></i></div><div><span data-preview-mobile-label>Mobile Exclusive <b>10%</b></span><strong data-preview-mobile>$114.75</strong><small data-preview-mobile-cut>−$12.75</small><i data-preview-net-bar style="--rate-width:76.5%"></i></div></div></div><div class="workspace-footer preview-note"><span>Each discount applies to the remaining balance.</span></div></div>'''

def developer_preview():
    names=['Environment','Rollout','Review']
    controls=''.join(f'<button type="button" id="preview-deploy-tab-{i}" class="{ "cover-stage-active" if i==1 else ""}" role="tab" aria-selected="{ "true" if i==1 else "false"}" aria-controls="preview-deploy-panel-{i}" tabindex="{0 if i==1 else -1}" data-preview-choice="{i}" disabled>{name}</button>' for i,name in enumerate(names))
    environment='''<div class="cover-environment preview-pane"><p>Environment</p><h4>staging-mesh</h4><div><span>24 cores</span><span>24 Gi</span></div><p>Mesh cluster pool</p></div><div class="preview-pane preview-detail"><p>Source</p><h4>98ds12df</h4><p class="preview-repository">actions/ansible-runner</p></div>'''
    rollout='''<div class="cover-environment preview-pane"><p>Environment</p><h4>staging-mesh</h4><div><span>24 cores</span><span>24 Gi</span></div></div><div class="cover-canary preview-pane preview-detail"><p>Rollout strategy</p><h4>Canary</h4><div class="cover-canary-sequence"><span>10%</span><span>20%</span><span>30%</span></div><div class="cover-canary-track"><i></i><i></i><i></i></div><p>300s ramp up · 900s monitoring</p></div>'''
    review='''<dl class="preview-review"><div><dt>Environment</dt><dd>staging-mesh · Mesh</dd></div><div><dt>Image</dt><dd>actions/ansible-runner · 98ds12df</dd></div><div><dt>Resources</dt><dd>24 cores · 24 Gi</dd></div><div><dt>Strategy</dt><dd>Canary · 10% → 20% → 30%</dd></div><div><dt>Targets</dt><dd>HK: 10 · SG: 10 · AM: 10 replicas</dd></div><div><dt>Monitoring</dt><dd>#devops_safe_app · 300s ramp up · 900s monitoring</dd></div></dl>'''
    panels=''.join(f'<div class="cover-deploy-body preview-body" id="preview-deploy-panel-{i}" role="tabpanel" aria-labelledby="preview-deploy-tab-{i}" data-preview-panel="{i}" {"" if i==1 else "hidden"}>{content}</div>' for i,content in enumerate([environment,rollout,review]))
    return f'''<div class="cover-deploy concept-shell concept-preview" data-preview-picker><div class="preview-header"><h4>Developer Portal</h4><span>Configure and review your deployment.</span></div><div class="cover-deploy-steps preview-choices" role="tablist" aria-label="Deployment example">{controls}</div><div class="preview-panels">{panels}</div><div class="cover-deploy-footer preview-note"><span>Hong Kong · Singapore · Amsterdam</span><span>10 replicas each</span></div></div>'''
