"""Original portfolio compositions inspired by Browserbase's graphic clarity."""
from html import escape


def flagship_hero():
    return '''<section class="studio-hero" data-cloud-scene aria-labelledby="hero-title">
<div class="hero-overline"><span>Product strategy · Design leadership</span><span>Bangkok, Thailand</span></div>
<div class="hero-stage"><div class="cloud-field" aria-hidden="true"><picture><source media="(max-width: 899px)" srcset="images/hero-halftone-800.png"><img class="cloud-poster" src="images/hero-halftone-1600.png" width="1600" height="758" fetchpriority="high" alt=""></picture><canvas class="cloud-canvas"></canvas></div>
<div class="hero-message"><p class="eyebrow">Designing products. Building teams.</p><h1 id="hero-title">Nicholas Gwee.<br><span>Product Design Lead.</span></h1><p class="hero-description">I make complex problems clear. I connect user needs, business strategy and interface craft — leading teams from framing the problem to shaping the product, guided by evidence.</p><div class="hero-actions"><a class="studio-button" href="#work">Explore my work <span aria-hidden="true">↓</span></a><a class="hero-secondary" href="#about">My approach <span aria-hidden="true">↗</span></a></div></div>
<div class="hero-landscape" aria-hidden="true"></div></div>
<div class="hero-footnote"><span>Featured work · Partner Growth Programs</span><span>Design strategy · Agoda</span><a href="partner-growth-programs.html">Read the flagship case study ↗</a></div></section>'''


def program_cover(programs, symbols):
    rows = ''.join(f'''<div class="catalog-preview-row {'is-selected' if i == 0 else ''}"><span class="catalog-glyph"><svg viewBox="0 0 48 48"><use href="images/program-symbols.svg#{symbols[i]}"/></svg></span><span><strong>{escape(name)}</strong><small>{escape(category)}</small></span><span class="catalog-row-arrow">›</span></div>''' for i,(name,category,*_) in enumerate(programs[:3]))
    return f'''<div class="product-preview catalog-preview"><div class="product-titlebar"><span class="product-brand">a<span>●</span></span><strong>Partner growth</strong><span>Program discovery</span></div><div class="cover-discovery-steps"><span class="is-active">Discover</span><span>Understand</span><span>Choose</span></div><div class="catalog-preview-body"><div class="catalog-preview-intro"><p>GROWTH PROGRAMS</p><h4>The right program.<br>A clearer next step.</h4></div><div class="catalog-preview-search"><svg viewBox="0 0 24 24"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg>Search by name or goal<span>All categories</span></div><div class="catalog-preview-split"><div><p class="workspace-label">PROGRAM CATALOG · 3 OF 8</p>{rows}</div><div class="catalog-preview-detail"><p class="workspace-label">CONVERSION</p><h4>{escape(programs[0][0])}</h4><p>{escape(programs[0][2])}</p><div class="workspace-rule"><span>How it works</span><p>{escape(programs[0][4])}</p></div></div></div></div><div class="workspace-footer"><span>Eight programs. One place to explore.</span><span>Original program mechanics</span></div></div>'''


def program_discovery(programs, symbols, compact=False):
    rows=[]
    for i,(name,category,desc,icon,detail) in enumerate(programs[:3] if compact else programs):
        rows.append(f'''<details class="program-tile" data-program data-category="{escape(category)}" data-name="{escape(name.lower())}"><summary><span class="catalog-glyph"><svg class="program-icon" viewBox="0 0 48 48" aria-hidden="true"><use href="images/program-symbols.svg#{symbols[i]}"/></svg></span><span class="growth-row-main"><strong>{escape(name)}</strong><span class="growth-row-description">{escape(desc)}</span></span><span class="growth-category">{escape(category)}</span><span class="program-open-label"><span class="sr-only">Program details</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></span></summary><div class="program-detail"><p class="growth-detail-label">How this program works</p><p>{escape(detail)}</p><span class="sample-label">Original program mechanics</span></div></details>''')
    filters='''<div class="discovery-controls"><label class="search-field"><span>Search programs</span><span class="growth-input-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg><input type="search" data-program-search placeholder="Search by name or goal" autocomplete="off" disabled></span></label><label class="category-field"><span>Category</span><select data-program-category disabled><option value="all">All categories</option>'''+''.join(f'<option>{escape(p[1])}</option>' for p in programs)+'''</select></label></div>'''
    return f'''<div class="discovery-ui growth-studio" data-discovery><div class="app-bar"><span class="app-mark" aria-hidden="true">a<span>●</span></span><strong>Partner growth</strong><span class="app-account"><small>Sample property</small>Maison Solara</span></div><div class="app-layout"><aside class="app-side" aria-label="Workflow context"><p class="app-side-label">WORKSPACE</p><span>Property</span><span>Reservations</span><span>Calendar</span><strong>Growth programs</strong><span>Payout</span><p class="app-side-note">Updated concept<br>Program discovery</p></aside><div class="app-content"><div class="growth-page-heading"><p class="growth-kicker">PROGRAM DISCOVERY</p><h2>Find your next growth opportunity.</h2><p>Explore the programs, understand the mechanics, choose your next step.</p></div><div class="growth-catalog">{filters}<div class="growth-list-header"><strong data-program-heading>All programs</strong><p class="search-count" aria-live="polite" data-program-count>8 programs</p><button type="button" class="growth-clear" data-program-clear hidden>Clear filters</button></div><div class="program-grid">{''.join(rows)}</div><div class="growth-empty" data-program-empty hidden><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg><strong>No matching programs</strong><p>Try another name or goal, or clear the filters to see all eight programs.</p></div></div><p class="growth-preview-note">Updated concept · Original program mechanics. No account changes.</p><noscript><p class="growth-preview-note">Search and category filtering require JavaScript. Expand any program to read its original mechanics.</p></noscript></div></div></div>'''


def rate_cover():
    return '''<div class="product-preview rate-preview"><div class="product-titlebar"><span class="rate-preview-mark" aria-hidden="true">%</span><strong>Net Rate Simulator</strong><span>USD / night</span></div><div class="workspace-location"><span>Discount setup</span><span>Calculation breakdown</span></div><div class="rate-preview-body"><div class="rate-preview-overview"><p class="rate-preview-eyebrow">ROOM RATE AFTER DISCOUNTS</p><div class="rate-preview-result"><strong>$114.75</strong><span>23.5%<small>effective discount</small></span></div><p class="rate-preview-exclusion">Before commission and taxes</p><div class="rate-preview-formula">150 × 0.85 × 0.90 = 114.75</div></div><div class="rate-preview-steps"><div><span>Starting room rate</span><strong>$150.00</strong><i style="--rate-width:100%"></i></div><div><span>Mega Sale <b>15%</b></span><strong>$127.50</strong><small>−$22.50</small><i style="--rate-width:85%"></i></div><div><span>Mobile Exclusive <b>10%</b></span><strong>$114.75</strong><small>−$12.75</small><i style="--rate-width:76.5%"></i></div></div></div><div class="workspace-footer"><span>Each discount applies to the remaining balance.</span></div></div>'''


def rate_calculator():
    return '''<div class="calculator-ui discount-studio discount-studio--calculator" data-calculator>
<div class="discount-app-header"><div class="discount-app-heading"><span class="rate-preview-mark" aria-hidden="true">%</span><h2 class="discount-app-title">Net Rate Simulator</h2></div><span class="discount-currency">USD / night</span></div>
<div class="calc-layout discount-workspace">
<form class="calc-form discount-settings">
<p class="ui-section-kicker">CONFIGURE</p><h3 class="discount-section-title">Discount setup</h3>
<div class="discount-interactive-fields">
<label class="rate-field" for="room-rate">Room rate (USD)<span class="input-money"><span aria-hidden="true">$</span><input id="room-rate" name="rate" type="number" min="0" max="1000000" step="0.01" value="150.00" required inputmode="decimal" aria-describedby="discount-rate-help discount-rate-error"><span class="discount-field-unit" aria-hidden="true">USD</span></span></label>
<p class="discount-field-help" id="discount-rate-help">Per night, before commission and taxes.</p>
<fieldset class="discount-promotions"><legend>Apply discounts in this order</legend>
<label class="promo-toggle"><input type="checkbox" name="mega" checked><span class="discount-promotion-copy"><strong>Mega Sale</strong><small>Advance booking</small></span><b class="discount-percent">15%</b></label>
<label class="promo-toggle"><input type="checkbox" name="mobile" checked><span class="discount-promotion-copy"><strong>Mobile Exclusive</strong><small>Mobile user</small></span><b class="discount-percent">10%</b></label>
<label class="promo-toggle ineligible"><input type="checkbox" disabled><span class="discount-promotion-copy"><strong>Early Bird</strong><small>20% · Not eligible tonight</small></span><b class="discount-ineligible-label">Ineligible</b></label>
</fieldset><button class="quiet-button calc-reset" type="reset">Reset example <span aria-hidden="true">↺</span></button>
</div>
<noscript><style>.discount-studio--calculator .discount-interactive-fields{display:none}</style><div class="discount-static-settings"><p class="discount-field-label">Room rate (USD)</p><div class="discount-static-field"><span>$150.00</span><span class="discount-field-unit">USD</span></div><p class="discount-field-help">Per night, before commission and taxes.</p><p class="discount-field-label discount-promotions-label">Discounts applied in order</p><div class="discount-static-promotion"><span class="discount-check" aria-hidden="true">✓</span><span><strong>Mega Sale</strong><small>Advance booking</small></span><b class="discount-percent">15%</b></div><div class="discount-static-promotion"><span class="discount-check" aria-hidden="true">✓</span><span><strong>Mobile Exclusive</strong><small>Mobile user</small></span><b class="discount-percent">10%</b></div><div class="discount-static-promotion"><span class="discount-check discount-check--off" aria-hidden="true"></span><span><strong>Early Bird</strong><small>20% · Not eligible tonight</small></span><b class="discount-ineligible-label">Ineligible</b></div><p class="noscript-note">Static example. Enable JavaScript to edit the rate and discounts.</p></div></noscript>
<p class="form-error" id="discount-rate-error" data-calc-error aria-live="polite"></p>
</form>
<div class="calc-result discount-summary">
<div class="discount-total"><span class="calc-result-label">Room rate after discounts</span><output id="net-rate" for="room-rate" data-net aria-live="polite" aria-atomic="true">$114.75</output><p class="calc-effective" data-effective>23.5% effective discount</p><p class="discount-exclusions">Before commission and taxes.</p></div>
<h3 class="discount-section-title" id="discount-breakdown-title">Calculation breakdown</h3><div class="discount-ledger-heading"><span>Applied in order</span><span>Remaining rate (USD)</span></div>
<div class="calc-ledger discount-ledger" data-ledger role="group" aria-labelledby="discount-breakdown-title">
<div><span>Room rate<small>Starting balance</small></span><strong>$150.00</strong><i style="--rate-width:100%" aria-hidden="true"></i></div>
<div><span>Mega Sale · 15%<small>15% of $150.00 · −$22.50</small></span><strong>$127.50</strong><i style="--rate-width:85%" aria-hidden="true"></i></div>
<div><span>Mobile Exclusive · 10%<small>10% of $127.50 · −$12.75</small></span><strong>$114.75</strong><i style="--rate-width:76.5%" aria-hidden="true"></i></div>
</div><p class="discount-total-cut" data-total-cut>Total discount · $35.25</p><div class="calc-formula">150 × 0.85 × 0.90 = 114.75</div><p class="discount-rule">Each discount applies to the remaining balance.</p>
</div></div><div class="discount-app-footer"><span>Updated concept · Illustrative room rate</span><span>No setup is saved.</span></div></div>'''


def developer_workflow():
    return r'''<div class="developer-ui" data-developer>
<div class="dev-toolbar"><span class="dev-brand"><span aria-hidden="true">▲</span> Developer portal</span><span class="dev-context">Deployment / devops-safe-app</span><span class="terminal-pill">Updated concept</span></div>
<div class="developer-layout"><aside class="developer-sidebar"><p>EXISTING TASK DOMAINS</p><span>Manage</span><span>Plan</span><strong>Build</strong><span>Secure</span><span>Monitor</span><p class="dev-sidebar-note">Deployment preview<br>Example settings</p></aside>
<form class="deploy-form"><ol class="deploy-steps" aria-label="Deployment steps"><li data-step-label="0" aria-current="step"><span aria-hidden="true">1</span> Environment</li><li data-step-label="1"><span aria-hidden="true">2</span> Rollout</li><li data-step-label="2"><span aria-hidden="true">3</span> Review</li></ol>
<div class="deploy-stage" data-step="0"><p class="app-eyebrow">ENVIRONMENT SETUP</p><h2>A clear place to start.</h2><p>Configure the environment before choosing how to roll out.</p>
<fieldset class="deploy-field-group"><legend>Environment &amp; source</legend><div class="deploy-fields"><label>Environment name<input name="environment" value="staging-mesh" required pattern="[a-zA-Z0-9_\-]+" maxlength="64" aria-describedby="environment-help"></label><label>Cluster pool<select name="pool"><option>Mesh</option><option>QA</option><option>Corp</option></select></label><label>Repository<select name="repository"><option>actions/ansible-runner</option></select></label><label>Image tag<input name="image" value="98ds12df" required maxlength="100"></label></div><p class="dev-field-help" id="environment-help">Environment name: letters, numbers, hyphens and underscores.</p></fieldset>
<fieldset class="deploy-field-group"><legend>Resource requests</legend><div class="deploy-fields"><label>CPU requests (cores)<input type="number" name="cpu" min="1" max="128" value="24" required></label><label>Memory requests (Gi)<input type="number" name="memory" min="1" max="512" value="24" required></label></div></fieldset>
<p class="dev-guidance">Ownership or AD request blocking progress? The original design supports leave and resume, with guidance at bottlenecks. This preview does not persist data.</p></div>
<div class="deploy-stage" data-step="1"><p class="app-eyebrow">ROLLOUT SETUP</p><h2>Make the rollout explicit.</h2>
<fieldset class="deploy-field-group"><legend>Rollout strategy</legend><label>Deployment strategy<select name="strategy"><option>Canary</option><option>Rolling update</option></select></label><p class="canary-path" data-canary>10% → 20% → 30%</p><p class="dev-field-help">Ramp up: 300 seconds · Monitoring: 900 seconds. Existing example settings.</p></fieldset>
<fieldset class="deploy-field-group"><legend>Targets &amp; monitoring</legend><div class="deploy-fields"><label>HK · Hong Kong replicas<input name="hk" type="number" min="1" max="100" value="10" required></label><label>SG · Singapore replicas<input name="sg" type="number" min="1" max="100" value="10" required></label><label>AM · Amsterdam replicas<input name="am" type="number" min="1" max="100" value="10" required></label><label>Slack channel<input name="slack" value="#devops_safe_app" required maxlength="100"></label></div></fieldset></div>
<div class="deploy-stage" data-step="2"><p class="app-eyebrow">REVIEW BEFORE DEPLOYMENT</p><h2>See the whole decision.</h2><p>Check the configuration before completing this preview.</p><dl class="deploy-review" data-deploy-review><div><dt>Environment</dt><dd>staging-mesh · Mesh</dd></div><div><dt>Image</dt><dd>actions/ansible-runner · 98ds12df</dd></div><div><dt>Resources</dt><dd>24 cores · 24 Gi</dd></div><div><dt>Strategy</dt><dd>Canary · 10% → 20% → 30%</dd></div><div><dt>Targets</dt><dd>HK: 10 · SG: 10 · AM: 10 replicas</dd></div><div><dt>Monitoring</dt><dd>#devops_safe_app · 300s ramp up · 900s monitoring</dd></div></dl></div>
<div class="deploy-actions"><button type="button" class="dev-back" data-deploy-back disabled>← Back</button><span data-step-count>Step 1 of 3</span><button type="button" class="dev-next" data-deploy-next disabled>Continue to rollout →</button></div><p class="deploy-status" data-deploy-status role="status"></p><p class="sample-label">Updated concept · Vercel-inspired workflow. Existing example values. Preview only: no infrastructure connection or deployment.</p><noscript><p>All three steps are shown as a static walkthrough. Enable JavaScript to try the preview.</p></noscript>
</form></div></div>'''
