"""Original portfolio compositions inspired by Browserbase's graphic clarity."""
from html import escape


def flagship_hero():
    return '''<section class="studio-hero" aria-labelledby="hero-title">
<div class="hero-overline"><span>Nicholas Gwee · Product Design Lead</span><span>Bangkok, Thailand</span></div>
<div class="hero-message"><p class="eyebrow">Featured work · Agoda</p><h1 id="hero-title">A clearer path<br><span>to partner growth.</span></h1><p class="hero-description">Design strategy, information architecture and interaction design for Agoda’s partner growth program suite.</p><div class="hero-actions"><a class="studio-button" href="partner-growth-programs.html">Explore Partner Growth Programs <span aria-hidden="true">↗</span></a><a class="hero-secondary" href="#work">More selected work <span aria-hidden="true">↓</span></a></div></div>
<div class="hero-landscape" aria-hidden="true"><img src="images/program-landscape.svg" width="1200" height="300" fetchpriority="high" alt=""><span class="landscape-label landscape-label--one">Promotions <b>↗</b></span><span class="landscape-label landscape-label--two">Agoda Growth Program <b>↗</b></span><span class="landscape-label landscape-label--three">Boost Rank <b>↗</b></span><svg class="landscape-signal" viewBox="0 0 1200 300"><path d="M100 270H285V206H590V130H840V70H1130"/></svg></div>
<div class="hero-footnote"><span>Partner Growth Programs</span><span>One hub. Eight existing programs.</span><span>Product strategy + interface craft</span></div></section>'''


def program_cover(programs, symbols):
    rows = ''.join(f'''<div class="catalog-preview-row"><span class="catalog-glyph catalog-glyph--{i}"><svg viewBox="0 0 48 48"><use href="images/program-symbols.svg#{symbols[i]}"/></svg></span><span><small>{escape(category)}</small><strong>{escape(name)}</strong></span><span class="catalog-row-arrow">↗</span></div>''' for i,(name,category,*_) in enumerate(programs[:3]))
    return f'''<div class="product-preview catalog-preview"><div class="product-titlebar"><span class="product-brand">a<span>●</span></span><strong>Partner growth</strong><span>Program catalog</span></div><div class="catalog-preview-body"><div class="catalog-preview-intro"><p>GROW YOUR PROPERTY</p><h4>Find your next<br>growth opportunity.</h4><span class="catalog-pixel" aria-hidden="true">↗</span></div><div class="catalog-preview-search"><svg viewBox="0 0 24 24"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg>Search programs<span>All categories⌄</span></div>{rows}<div class="product-preview-note"><span>Showing 3 of 8 programs</span><span>Discover · Compare · Review</span></div></div></div>'''


def program_discovery(programs, symbols, compact=False):
    rows=[]
    for i,(name,category,desc,icon,detail) in enumerate(programs[:3] if compact else programs):
        rows.append(f'''<details class="program-tile" data-program data-category="{escape(category)}" data-name="{escape(name.lower())}"><summary><span class="catalog-glyph catalog-glyph--{i%3}"><svg class="program-icon" viewBox="0 0 48 48" aria-hidden="true"><use href="images/program-symbols.svg#{symbols[i]}"/></svg></span><span class="growth-category">{escape(category)}</span><span class="growth-row-main"><strong>{escape(name)}</strong><span class="growth-row-description">{escape(desc)}</span></span><span class="program-open-label">Program details <span aria-hidden="true">↗</span></span></summary><div class="program-detail"><p class="growth-detail-label">How this program works</p><p>{escape(detail)}</p><span class="sample-label">Original program mechanics</span></div></details>''')
    filters='''<div class="discovery-controls"><label class="search-field"><span>Search programs</span><span class="growth-input-wrap"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg><input type="search" data-program-search placeholder="Search by name or goal" autocomplete="off"></span></label><label class="category-field"><span>Category</span><select data-program-category><option value="all">All categories</option>'''+''.join(f'<option>{escape(p[1])}</option>' for p in programs)+'''</select></label></div>'''
    return f'''<div class="discovery-ui growth-studio" data-discovery><div class="app-bar"><span class="app-mark" aria-hidden="true">a<span>●</span></span><strong>Partner growth</strong><span class="app-account"><small>Sample property</small>Maison Solara</span></div><div class="app-layout"><aside class="app-side" aria-label="Workflow context"><p class="app-side-label">WORKSPACE</p><span>Property</span><span>Reservations</span><span>Calendar</span><strong>Growth programs</strong><span>Payout</span><p class="app-side-note">Updated concept<br>Program discovery</p></aside><div class="app-content"><div class="growth-page-heading"><p class="growth-kicker">PROGRAM DISCOVERY</p><h2>Find your next<br>growth opportunity.</h2><p>Explore the programs, understand the mechanics, choose your next step.</p><span class="catalog-pixel" aria-hidden="true">↗</span></div>{filters}<div class="growth-list-header"><strong>All programs</strong><p class="search-count" aria-live="polite" data-program-count>8 programs</p></div><div class="program-grid">{''.join(rows)}</div><p class="growth-preview-note">Updated concept · Original program mechanics. No account changes.</p><noscript><p class="growth-preview-note">Search and category filtering require JavaScript. Expand any program to read its original mechanics.</p></noscript></div></div></div>'''


def rate_cover():
    return '''<div class="product-preview rate-preview"><div class="product-titlebar"><span class="rate-preview-mark" aria-hidden="true">%</span><strong>Net Rate Simulator</strong><span>USD / night</span></div><div class="rate-preview-body"><p class="rate-preview-eyebrow">ROOM RATE AFTER DISCOUNTS</p><div class="rate-preview-result"><strong>$114.75</strong><span>23.5%<small>effective discount</small></span></div><p class="rate-preview-exclusion">Before commission and taxes</p><div class="rate-preview-steps"><div><span>Starting room rate</span><strong>$150.00</strong><i style="--rate-width:100%"></i></div><div><span>Mega Sale <b>15%</b></span><strong>$127.50</strong><small>−$22.50</small><i style="--rate-width:85%"></i></div><div><span>Mobile Exclusive <b>10%</b></span><strong>$114.75</strong><small>−$12.75</small><i style="--rate-width:76.5%"></i></div></div><div class="rate-preview-formula">150 × 0.85 × 0.90 = 114.75</div><p class="product-preview-note">Each discount applies to the remaining balance.</p></div></div>'''
